import { useEffect, useState } from 'react'
import { site, skillGroups, gmailComposeUrl } from './data'
import { Reveal } from './components/Reveal'
import { Arrow, Mark } from './components/Icon'
import { SkillIcon } from './components/SkillIcon'

const links = [['Home','home'], ['About','about'], ['Projects','projects'], ['Skills','skills'], ['Contact','contact']] as const

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [active, setActive] = useState('home')
  useEffect(() => { const sections = links.map(([, id]) => document.getElementById(id)).filter(Boolean) as HTMLElement[]; const observer = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && setActive(e.target.id)), { rootMargin: '-45% 0px -45% 0px' }); sections.forEach(s => observer.observe(s)); return () => observer.disconnect() }, [])
  const go = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }
  return <><div className="progress" aria-hidden="true" />
    <header><nav className="nav wrap" aria-label="Primary navigation"><Mark /><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation"><i /><i /></button><div className={`navlinks ${menuOpen ? 'open' : ''}`}>{links.map(([label, id]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => go(id)}>{label}</button>)}</div><button onClick={() => go('contact')} className="nav-cta">Let’s talk <Arrow /></button></nav></header>
    <main>
      <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow reveal">AVAILABLE FOR NEW IDEAS <b /></p><h1 className="reveal">Sedrat<br/><em>Abdelmoumene</em></h1><p className="arabic reveal" lang="ar" dir="rtl">{site.arabicName}</p><p className="role reveal">{site.role}</p><p className="intro reveal">Hey, I’m Moumene. I’m a developer and creative problem-solver who loves turning ideas into real, interactive experiences. I’m focused on web development, programming, AI, and building projects that are actually useful — while constantly learning, experimenting, and pushing my skills further.</p><p className="statement reveal">I don’t just want to use technology. <span>I want to build with it.</span></p><div className="hero-actions reveal"><button className="button primary" onClick={() => go('contact')}>Let’s Work Together <Arrow /></button><button className="button secondary" onClick={() => go('projects')}>View My Work <Arrow /></button></div></div><div className="portrait reveal"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="portrait-label">01 <span>Developer / Builder</span></div><img src="/src/assets/profile/profile.png" alt="Portrait of Sedrat Abdelmoumene" fetchPriority="high" /></div><div className="scroll-hint">SCROLL TO EXPLORE <span /></div></section>
      <section id="about" className="about wrap section"><Reveal><p className="eyebrow">01 / ABOUT</p><div className="section-grid"><h2>Curious by nature.<br/><em>Practical by choice.</em></h2><div><p className="lead">I enjoy the process of taking an idea from its first rough sketch to something people can actually use.</p><p>Whether I’m building a web interface, exploring an AI tool, or learning a new technology, I’m drawn to the useful details: clear experiences, real problems, and the satisfaction of making things work.</p><a href="#contact" onClick={e => { e.preventDefault(); go('contact') }} className="text-link">A little idea can go a long way <Arrow /></a></div></div></Reveal></section>
      <section id="projects" className="projects section"><div className="wrap"><Reveal><p className="eyebrow">02 / SELECTED WORK</p><div className="section-heading"><h2>Featured <em>Project.</em></h2><p>One focused product, built around a practical everyday experience.</p></div></Reveal><Reveal><article className="project-card"><div className="project-image"><div className="project-visual-heading"><span>01 / PRODUCT PREVIEW</span><h3>Restaurant Ordering<br/><em>System</em></h3></div><div className="project-screen"><img src={site.projectImage} alt="Restaurant Ordering System customer menu interface" loading="lazy" /><a className="screen-link" href={site.projectUrl} target="_blank" rel="noreferrer">View Project <Arrow /></a></div></div><div className="project-info"><p className="project-number">01 — IN DEVELOPMENT</p><p className="project-summary">A modern QR-based restaurant ordering system designed to give customers a digital menu and a convenient online ordering experience.</p><div className="facts"><div><small>TYPE</small><span>Web Application</span></div><div><small>FOCUS</small><span>Restaurant / Digital Ordering</span></div><div><small>STATUS</small><span>In Development</span></div><div><small>SOURCE</small><span>Private</span></div></div><p className="technology-note">Technologies: <strong>Add actual technologies here</strong></p><p className="hover-note">Hover the preview to explore the project <Arrow /></p></div></article></Reveal><Reveal><div className="coming"><span>✦</span><div><strong>More projects are coming.</strong><p>I’m continuously building, experimenting, and turning new ideas into real products.</p></div></div></Reveal></div></section>
      <section id="skills" className="skills wrap section"><Reveal><p className="eyebrow">03 / CAPABILITIES</p><div className="section-heading"><h2>Skills &amp; <em>Tools.</em></h2><p>A growing toolkit for turning ideas into thoughtful digital work.</p></div></Reveal><div className="skill-groups">{skillGroups.map((group, groupIndex) => <Reveal key={group.title}><article className="skill-group"><div className="skill-group-heading"><span>0{groupIndex + 1}</span><div><h3>{group.title}</h3><p>{group.note}</p></div></div><div className="skill-badges">{group.skills.map(([skill]) => <div className="skill-badge" key={skill} tabIndex={0} aria-label={skill}><div className="skill-logo" aria-hidden="true"><SkillIcon name={skill} /></div><strong>{skill}</strong></div>)}</div></article></Reveal>)}</div></section>
      <section id="contact" className="contact section"><div className="wrap"><Reveal><p className="eyebrow">04 / CONTACT</p><div className="contact-top"><div><h2>Let’s build<br/><em>something.</em></h2><p>Have an idea, project, or opportunity? Let’s turn it into something real.</p></div><a className="button primary" href={gmailComposeUrl} target="_blank" rel="noreferrer">Let’s Work Together <Arrow /></a></div></Reveal><div className="contact-grid"><a href={gmailComposeUrl} target="_blank" rel="noreferrer"><small>EMAIL</small><strong>{site.email}</strong><Arrow /></a><a href={site.whatsapp} target="_blank" rel="noreferrer"><small>WHATSAPP</small><strong>+213 794 868 404</strong><Arrow /></a><a href={site.github} target="_blank" rel="noreferrer"><small>GITHUB</small><strong>Sedrat-Abdelmoumene</strong><Arrow /></a></div></div></section>
    </main><footer className="wrap"><Mark /><p>© 2026 Sedrat Abdelmoumene</p><a href="#home">Back to top ↑</a></footer></>
}
